"""adding lastbooks

Revision ID: 1416e28ff914
Revises: e9ee6c008a2b
Create Date: 2024-06-11 12:14:30.540484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1416e28ff914'
down_revision = 'e9ee6c008a2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('last_book_visits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name=op.f('fk_last_book_visits_book_id_books')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_last_book_visits_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_last_book_visits'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('last_book_visits')
    # ### end Alembic commands ###
