"""delete cascade2

Revision ID: 97e4f3b19ab3
Revises: f212185aea11
Create Date: 2024-06-12 17:17:12.008194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97e4f3b19ab3'
down_revision = 'f212185aea11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_constraint('fk_books_image_id_images', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_books_image_id_images'), 'images', ['image_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_books_image_id_images'), type_='foreignkey')
        batch_op.create_foreign_key('fk_books_image_id_images', 'images', ['image_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
