"""delete cascade

Revision ID: f212185aea11
Revises: 1416e28ff914
Create Date: 2024-06-12 17:12:18.833919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f212185aea11'
down_revision = '1416e28ff914'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_constraint('fk_books_image_id_images', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_books_image_id_images'), 'images', ['image_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('books_genres', schema=None) as batch_op:
        batch_op.drop_constraint('fk_books_genres_genre_id_genres', type_='foreignkey')
        batch_op.drop_constraint('fk_books_genres_book_id_books', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_books_genres_book_id_books'), 'books', ['book_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_books_genres_genre_id_genres'), 'genres', ['genre_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books_genres', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_books_genres_genre_id_genres'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_books_genres_book_id_books'), type_='foreignkey')
        batch_op.create_foreign_key('fk_books_genres_book_id_books', 'books', ['book_id'], ['id'])
        batch_op.create_foreign_key('fk_books_genres_genre_id_genres', 'genres', ['genre_id'], ['id'])

    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_books_image_id_images'), type_='foreignkey')
        batch_op.create_foreign_key('fk_books_image_id_images', 'images', ['image_id'], ['id'])

    # ### end Alembic commands ###
